### ISSUE TITLE
Get MealDay component MVP

### ISSUE THREAD

**Issue by francinebc** [harakeke-2019/food-mood#98]
1. Shows all the meals of the day, and their moods (emoji and time)
2. If you click on a meal it will redirect to '/addMood/:mealId' to add a new mood
3. Add a plus icon so users can add a new mood. This will redirect to '/addMeal'

This will get the list of meals from props, passed down from Calendar component

**Comment by benlittlenz** [comment]
Can now show all meals on specific day and moods. Can also redirect to add a new mood and a link to add a new meal
closes #98
